/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->BreakAlgebraicLoop_DSTATE);
   memcpy(&pDst->BreakAlgebraicLoop_DSTATE, &pSrc->BreakAlgebraicLoop_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PmIntegrator_DSTATE);
   memcpy(&pDst->PmIntegrator_DSTATE, &pSrc->PmIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->GeneratedFilterBlock_states);
   memcpy(&pDst->GeneratedFilterBlock_states, &pSrc->GeneratedFilterBlock_states, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator1_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator1_DSTATE, &pSrc->DiscreteTimeIntegrator1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->fluxes_DSTATE);
   memcpy(&pDst->fluxes_DSTATE, &pSrc->fluxes_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE, &pSrc->DiscreteTimeIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->voltages_DSTATE);
   memcpy(&pDst->voltages_DSTATE, &pSrc->voltages_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE);
   memcpy(&pDst->Integrator_DSTATE, &pSrc->Integrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE);
   memcpy(&pDst->Filter_DSTATE, &pSrc->Filter_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_i);
   memcpy(&pDst->Integrator_DSTATE_i, &pSrc->Integrator_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_p);
   memcpy(&pDst->Filter_DSTATE_p, &pSrc->Filter_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_h);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_h, &pSrc->DiscreteTimeIntegrator_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_o);
   memcpy(&pDst->Integrator_DSTATE_o, &pSrc->Integrator_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_l);
   memcpy(&pDst->Filter_DSTATE_l, &pSrc->Filter_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_ob);
   memcpy(&pDst->Integrator_DSTATE_ob, &pSrc->Integrator_DSTATE_ob, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_p5);
   memcpy(&pDst->Filter_DSTATE_p5, &pSrc->Filter_DSTATE_p5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_hc);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_hc, &pSrc->DiscreteTimeIntegrator_DSTAT_hc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_DSTATE);
   memcpy(&pDst->Delay_DSTATE, &pSrc->Delay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_DSTATE_a);
   memcpy(&pDst->Delay_DSTATE_a, &pSrc->Delay_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_DSTATE_i);
   memcpy(&pDst->Delay_DSTATE_i, &pSrc->Delay_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNamesel751te);
   memcpy(&pDst->SSNVersion19SSNFileNamesel751te, &pSrc->SSNVersion19SSNFileNamesel751te, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->StateSpace_xn_g1);
   memcpy(&pDst->StateSpace_xn_g1, &pSrc->StateSpace_xn_g1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNamesel751_h);
   memcpy(&pDst->SSNVersion19SSNFileNamesel751_h, &pSrc->SSNVersion19SSNFileNamesel751_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNamesel75_hg);
   memcpy(&pDst->SSNVersion19SSNFileNamesel75_hg, &pSrc->SSNVersion19SSNFileNamesel75_hg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNamesel7_hgh);
   memcpy(&pDst->SSNVersion19SSNFileNamesel7_hgh, &pSrc->SSNVersion19SSNFileNamesel7_hgh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNamesel_hgha);
   memcpy(&pDst->SSNVersion19SSNFileNamesel_hgha, &pSrc->SSNVersion19SSNFileNamesel_hgha, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNamese_hghah);
   memcpy(&pDst->SSNVersion19SSNFileNamese_hghah, &pSrc->SSNVersion19SSNFileNamese_hghah, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNames_hghahz);
   memcpy(&pDst->SSNVersion19SSNFileNames_hghahz, &pSrc->SSNVersion19SSNFileNames_hghahz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileName_hghahzd);
   memcpy(&pDst->SSNVersion19SSNFileName_hghahzd, &pSrc->SSNVersion19SSNFileName_hghahzd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNam_hghahzd0);
   memcpy(&pDst->SSNVersion19SSNFileNam_hghahzd0, &pSrc->SSNVersion19SSNFileNam_hghahzd0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileNa_hghahzd0h);
   memcpy(&pDst->SSNVersion19SSNFileNa_hghahzd0h, &pSrc->SSNVersion19SSNFileNa_hghahzd0h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFileN_hghahzd0hp);
   memcpy(&pDst->SSNVersion19SSNFileN_hghahzd0hp, &pSrc->SSNVersion19SSNFileN_hghahzd0hp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFile_hghahzd0hp3);
   memcpy(&pDst->SSNVersion19SSNFile_hghahzd0hp3, &pSrc->SSNVersion19SSNFile_hghahzd0hp3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFil_hghahzd0hp3w);
   memcpy(&pDst->SSNVersion19SSNFil_hghahzd0hp3w, &pSrc->SSNVersion19SSNFil_hghahzd0hp3w, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNFi_hghahzd0hp3wu);
   memcpy(&pDst->SSNVersion19SSNFi_hghahzd0hp3wu, &pSrc->SSNVersion19SSNFi_hghahzd0hp3wu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSNF_hghahzd0hp3wu2);
   memcpy(&pDst->SSNVersion19SSNF_hghahzd0hp3wu2, &pSrc->SSNVersion19SSNF_hghahzd0hp3wu2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSN_hghahzd0hp3wu2e);
   memcpy(&pDst->SSNVersion19SSN_hghahzd0hp3wu2e, &pSrc->SSNVersion19SSN_hghahzd0hp3wu2e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSN_b);
   memcpy(&pDst->SSNVersion19SSN_b, &pSrc->SSNVersion19SSN_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSN_a);
   memcpy(&pDst->SSNVersion19SSN_a, &pSrc->SSNVersion19SSN_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SSNVersion19SSN_e);
   memcpy(&pDst->SSNVersion19SSN_e, &pSrc->SSNVersion19SSN_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_b);
   memcpy(&pDst->Integrator_DSTATE_b, &pSrc->Integrator_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_k);
   memcpy(&pDst->Filter_DSTATE_k, &pSrc->Filter_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_c);
   memcpy(&pDst->Integrator_DSTATE_c, &pSrc->Integrator_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_j);
   memcpy(&pDst->Filter_DSTATE_j, &pSrc->Filter_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_k);
   memcpy(&pDst->Integrator_DSTATE_k, &pSrc->Integrator_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_a);
   memcpy(&pDst->Filter_DSTATE_a, &pSrc->Filter_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator2_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator2_DSTATE, &pSrc->DiscreteTimeIntegrator2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_ch);
   memcpy(&pDst->Integrator_DSTATE_ch, &pSrc->Integrator_DSTATE_ch, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->fIntegrator_DSTATE);
   memcpy(&pDst->fIntegrator_DSTATE, &pSrc->fIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->VariableIntegerDelay_DSTATE);
   memcpy(&pDst->VariableIntegerDelay_DSTATE, &pSrc->VariableIntegerDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay2_DSTATE);
   memcpy(&pDst->UnitDelay2_DSTATE, &pSrc->UnitDelay2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_p);
   memcpy(&pDst->Integrator_DSTATE_p, &pSrc->Integrator_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_d);
   memcpy(&pDst->Filter_DSTATE_d, &pSrc->Filter_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->GeneratedFilterBlock_states_n);
   memcpy(&pDst->GeneratedFilterBlock_states_n, &pSrc->GeneratedFilterBlock_states_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LoadThermalMass50degMBTU_DSTATE);
   memcpy(&pDst->LoadThermalMass50degMBTU_DSTATE, &pSrc->LoadThermalMass50degMBTU_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RemoveAlgebraicLoop1_DSTATE);
   memcpy(&pDst->RemoveAlgebraicLoop1_DSTATE, &pSrc->RemoveAlgebraicLoop1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RemoveAlgebraicLoop_DSTATE);
   memcpy(&pDst->RemoveAlgebraicLoop_DSTATE, &pSrc->RemoveAlgebraicLoop_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_DSTATE_jk);
   memcpy(&pDst->Filter_DSTATE_jk, &pSrc->Filter_DSTATE_jk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_DSTATE_d);
   memcpy(&pDst->Integrator_DSTATE_d, &pSrc->Integrator_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE);
   memcpy(&pDst->DiscreteStateSpace_DSTATE, &pSrc->DiscreteStateSpace_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE);
   memcpy(&pDst->UnitDelay1_DSTATE, &pSrc->UnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_o);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_o, &pSrc->DiscreteStateSpace_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_d);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_d, &pSrc->DiscreteStateSpace_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_c);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_c, &pSrc->DiscreteStateSpace_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_j);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_j, &pSrc->DiscreteStateSpace_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Initialspeed400RPM_DSTATE);
   memcpy(&pDst->Initialspeed400RPM_DSTATE, &pSrc->Initialspeed400RPM_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_e);
   memcpy(&pDst->UnitDelay_DSTATE_e, &pSrc->UnitDelay_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrtor_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrtor_DSTATE, &pSrc->DiscreteTimeIntegrtor_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_f);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_f, &pSrc->DiscreteTimeIntegrator_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator1_DSTAT_b);
   memcpy(&pDst->DiscreteTimeIntegrator1_DSTAT_b, &pSrc->DiscreteTimeIntegrator1_DSTAT_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrtor_DSTATE_d);
   memcpy(&pDst->DiscreteTimeIntegrtor_DSTATE_d, &pSrc->DiscreteTimeIntegrtor_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_l);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_l, &pSrc->DiscreteTimeIntegrator_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrtor_DSTATE_n);
   memcpy(&pDst->DiscreteTimeIntegrtor_DSTATE_n, &pSrc->DiscreteTimeIntegrtor_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE);
   memcpy(&pDst->DelayInput1_DSTATE, &pSrc->DelayInput1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n);
   memcpy(&pDst->UnitDelay_DSTATE_n, &pSrc->UnitDelay_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_e);
   memcpy(&pDst->Integ4_DSTATE_e, &pSrc->Integ4_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_p);
   memcpy(&pDst->UnitDelay_DSTATE_p, &pSrc->UnitDelay_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h);
   memcpy(&pDst->UnitDelay_DSTATE_h, &pSrc->UnitDelay_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_f5);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_f5, &pSrc->DiscreteTimeIntegrator_DSTAT_f5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE);
   memcpy(&pDst->UD_DSTATE, &pSrc->UD_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d);
   memcpy(&pDst->UnitDelay_DSTATE_d, &pSrc->UnitDelay_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_cp);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_cp, &pSrc->DiscreteStateSpace_DSTATE_cp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_h);
   memcpy(&pDst->Integ4_DSTATE_h, &pSrc->Integ4_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_nq);
   memcpy(&pDst->UnitDelay_DSTATE_nq, &pSrc->UnitDelay_DSTATE_nq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE, &pSrc->FixPtUnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_pb);
   memcpy(&pDst->UnitDelay_DSTATE_pb, &pSrc->UnitDelay_DSTATE_pb, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_n);
   memcpy(&pDst->Integ4_DSTATE_n, &pSrc->Integ4_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_do);
   memcpy(&pDst->UnitDelay_DSTATE_do, &pSrc->UnitDelay_DSTATE_do, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_o);
   memcpy(&pDst->UnitDelay1_DSTATE_o, &pSrc->UnitDelay1_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_states);
   memcpy(&pDst->DiscreteDerivative_states, &pSrc->DiscreteDerivative_states, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_d);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_d, &pSrc->DiscreteTimeIntegrator_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE);
   memcpy(&pDst->Delay_x1_DSTATE, &pSrc->Delay_x1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE);
   memcpy(&pDst->Delay_x2_DSTATE, &pSrc->Delay_x2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_a);
   memcpy(&pDst->Integ4_DSTATE_a, &pSrc->Integ4_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_pp);
   memcpy(&pDst->UnitDelay_DSTATE_pp, &pSrc->UnitDelay_DSTATE_pp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_c);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_c, &pSrc->FixPtUnitDelay1_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_f);
   memcpy(&pDst->UnitDelay_DSTATE_f, &pSrc->UnitDelay_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_c);
   memcpy(&pDst->Integ4_DSTATE_c, &pSrc->Integ4_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_c);
   memcpy(&pDst->UnitDelay_DSTATE_c, &pSrc->UnitDelay_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_j);
   memcpy(&pDst->UnitDelay1_DSTATE_j, &pSrc->UnitDelay1_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_states_p);
   memcpy(&pDst->DiscreteDerivative_states_p, &pSrc->DiscreteDerivative_states_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_ls);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_ls, &pSrc->DiscreteTimeIntegrator_DSTAT_ls, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x1_DSTATE_n);
   memcpy(&pDst->Delay_x1_DSTATE_n, &pSrc->Delay_x1_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Delay_x2_DSTATE_o);
   memcpy(&pDst->Delay_x2_DSTATE_o, &pSrc->Delay_x2_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_f);
   memcpy(&pDst->Integ4_DSTATE_f, &pSrc->Integ4_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_db);
   memcpy(&pDst->UnitDelay_DSTATE_db, &pSrc->UnitDelay_DSTATE_db, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_k);
   memcpy(&pDst->Integ4_DSTATE_k, &pSrc->Integ4_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_e0);
   memcpy(&pDst->UnitDelay_DSTATE_e0, &pSrc->UnitDelay_DSTATE_e0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ex);
   memcpy(&pDst->Integ4_DSTATE_ex, &pSrc->Integ4_DSTATE_ex, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_o);
   memcpy(&pDst->UnitDelay_DSTATE_o, &pSrc->UnitDelay_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_fr);
   memcpy(&pDst->Integ4_DSTATE_fr, &pSrc->Integ4_DSTATE_fr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_g);
   memcpy(&pDst->UnitDelay_DSTATE_g, &pSrc->UnitDelay_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_d);
   memcpy(&pDst->UnitDelay1_DSTATE_d, &pSrc->UnitDelay1_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_cv);
   memcpy(&pDst->Integ4_DSTATE_cv, &pSrc->Integ4_DSTATE_cv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_en);
   memcpy(&pDst->UnitDelay_DSTATE_en, &pSrc->UnitDelay_DSTATE_en, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_dv);
   memcpy(&pDst->UnitDelay1_DSTATE_dv, &pSrc->UnitDelay1_DSTATE_dv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_hm);
   memcpy(&pDst->Integ4_DSTATE_hm, &pSrc->Integ4_DSTATE_hm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_pn);
   memcpy(&pDst->UnitDelay_DSTATE_pn, &pSrc->UnitDelay_DSTATE_pn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_i);
   memcpy(&pDst->UnitDelay1_DSTATE_i, &pSrc->UnitDelay1_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_aa);
   memcpy(&pDst->Integ4_DSTATE_aa, &pSrc->Integ4_DSTATE_aa, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_a);
   memcpy(&pDst->UnitDelay_DSTATE_a, &pSrc->UnitDelay_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_jp);
   memcpy(&pDst->UnitDelay1_DSTATE_jp, &pSrc->UnitDelay1_DSTATE_jp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_o);
   memcpy(&pDst->Integ4_DSTATE_o, &pSrc->Integ4_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_gi);
   memcpy(&pDst->UnitDelay_DSTATE_gi, &pSrc->UnitDelay_DSTATE_gi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_b);
   memcpy(&pDst->UnitDelay1_DSTATE_b, &pSrc->UnitDelay1_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_cg);
   memcpy(&pDst->Integ4_DSTATE_cg, &pSrc->Integ4_DSTATE_cg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ez);
   memcpy(&pDst->UnitDelay_DSTATE_ez, &pSrc->UnitDelay_DSTATE_ez, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_c);
   memcpy(&pDst->UnitDelay1_DSTATE_c, &pSrc->UnitDelay1_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_eh);
   memcpy(&pDst->Integ4_DSTATE_eh, &pSrc->Integ4_DSTATE_eh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_l);
   memcpy(&pDst->UnitDelay_DSTATE_l, &pSrc->UnitDelay_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_dh);
   memcpy(&pDst->UnitDelay1_DSTATE_dh, &pSrc->UnitDelay1_DSTATE_dh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_j);
   memcpy(&pDst->Integ4_DSTATE_j, &pSrc->Integ4_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_l4);
   memcpy(&pDst->UnitDelay_DSTATE_l4, &pSrc->UnitDelay_DSTATE_l4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_a);
   memcpy(&pDst->UnitDelay1_DSTATE_a, &pSrc->UnitDelay1_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ha);
   memcpy(&pDst->Integ4_DSTATE_ha, &pSrc->Integ4_DSTATE_ha, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n2);
   memcpy(&pDst->UnitDelay_DSTATE_n2, &pSrc->UnitDelay_DSTATE_n2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_e);
   memcpy(&pDst->UnitDelay1_DSTATE_e, &pSrc->UnitDelay1_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ab);
   memcpy(&pDst->Integ4_DSTATE_ab, &pSrc->Integ4_DSTATE_ab, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_j);
   memcpy(&pDst->UnitDelay_DSTATE_j, &pSrc->UnitDelay_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay1_DSTATE_i1);
   memcpy(&pDst->UnitDelay1_DSTATE_i1, &pSrc->UnitDelay1_DSTATE_i1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Lmd_sat_DSTATE);
   memcpy(&pDst->Lmd_sat_DSTATE, &pSrc->Lmd_sat_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Lmq_sat_DSTATE);
   memcpy(&pDst->Lmq_sat_DSTATE, &pSrc->Lmq_sat_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_PreviousInput);
   memcpy(&pDst->Memory5_PreviousInput, &pSrc->Memory5_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput);
   memcpy(&pDst->Memory1_PreviousInput, &pSrc->Memory1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput);
   memcpy(&pDst->Memory2_PreviousInput, &pSrc->Memory2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_PreviousInput);
   memcpy(&pDst->Memory3_PreviousInput, &pSrc->Memory3_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_PreviousInput_o);
   memcpy(&pDst->Memory5_PreviousInput_o, &pSrc->Memory5_PreviousInput_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_h);
   memcpy(&pDst->Memory1_PreviousInput_h, &pSrc->Memory1_PreviousInput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput_k);
   memcpy(&pDst->Memory2_PreviousInput_k, &pSrc->Memory2_PreviousInput_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_PreviousInput_m);
   memcpy(&pDst->Memory3_PreviousInput_m, &pSrc->Memory3_PreviousInput_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_1_PreviousInput);
   memcpy(&pDst->Memory5_1_PreviousInput, &pSrc->Memory5_1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_2_PreviousInput);
   memcpy(&pDst->Memory5_2_PreviousInput, &pSrc->Memory5_2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_3_PreviousInput);
   memcpy(&pDst->Memory5_3_PreviousInput, &pSrc->Memory5_3_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_ha);
   memcpy(&pDst->Memory1_PreviousInput_ha, &pSrc->Memory1_PreviousInput_ha, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput_b);
   memcpy(&pDst->Memory2_PreviousInput_b, &pSrc->Memory2_PreviousInput_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_i);
   memcpy(&pDst->Memory1_PreviousInput_i, &pSrc->Memory1_PreviousInput_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput_o);
   memcpy(&pDst->Memory2_PreviousInput_o, &pSrc->Memory2_PreviousInput_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin);
   memcpy(&pDst->lastSin, &pSrc->lastSin, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos);
   memcpy(&pDst->lastCos, &pSrc->lastCos, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_g);
   memcpy(&pDst->lastSin_g, &pSrc->lastSin_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_p);
   memcpy(&pDst->lastCos_p, &pSrc->lastCos_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_h);
   memcpy(&pDst->lastSin_h, &pSrc->lastSin_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_o);
   memcpy(&pDst->lastCos_o, &pSrc->lastCos_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY);
   memcpy(&pDst->PrevY, &pSrc->PrevY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY_o);
   memcpy(&pDst->PrevY_o, &pSrc->PrevY_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_PreviousInput_n);
   memcpy(&pDst->Memory5_PreviousInput_n, &pSrc->Memory5_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_p);
   memcpy(&pDst->Memory1_PreviousInput_p, &pSrc->Memory1_PreviousInput_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput_a);
   memcpy(&pDst->Memory2_PreviousInput_a, &pSrc->Memory2_PreviousInput_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_PreviousInput_n);
   memcpy(&pDst->Memory3_PreviousInput_n, &pSrc->Memory3_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_g);
   memcpy(&pDst->Memory_PreviousInput_g, &pSrc->Memory_PreviousInput_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_k);
   memcpy(&pDst->Memory_PreviousInput_k, &pSrc->Memory_PreviousInput_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_b);
   memcpy(&pDst->Memory_PreviousInput_b, &pSrc->Memory_PreviousInput_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_PreviousInput_l);
   memcpy(&pDst->Memory3_PreviousInput_l, &pSrc->Memory3_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory4_PreviousInput);
   memcpy(&pDst->Memory4_PreviousInput, &pSrc->Memory4_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_PreviousInput_l);
   memcpy(&pDst->Memory5_PreviousInput_l, &pSrc->Memory5_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory6_PreviousInput);
   memcpy(&pDst->Memory6_PreviousInput, &pSrc->Memory6_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_tmp);
   memcpy(&pDst->DiscreteDerivative_tmp, &pSrc->DiscreteDerivative_tmp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY_f);
   memcpy(&pDst->PrevY_f, &pSrc->PrevY_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_PreviousInput_j);
   memcpy(&pDst->Memory3_PreviousInput_j, &pSrc->Memory3_PreviousInput_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory4_PreviousInput_j);
   memcpy(&pDst->Memory4_PreviousInput_j, &pSrc->Memory4_PreviousInput_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_PreviousInput_b);
   memcpy(&pDst->Memory5_PreviousInput_b, &pSrc->Memory5_PreviousInput_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory6_PreviousInput_d);
   memcpy(&pDst->Memory6_PreviousInput_d, &pSrc->Memory6_PreviousInput_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteDerivative_tmp_j);
   memcpy(&pDst->DiscreteDerivative_tmp_j, &pSrc->DiscreteDerivative_tmp_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PrevY_b);
   memcpy(&pDst->PrevY_b, &pSrc->PrevY_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_1_PreviousInput_i);
   memcpy(&pDst->Memory5_1_PreviousInput_i, &pSrc->Memory5_1_PreviousInput_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_2_PreviousInput_p);
   memcpy(&pDst->Memory5_2_PreviousInput_p, &pSrc->Memory5_2_PreviousInput_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory5_3_PreviousInput_h);
   memcpy(&pDst->Memory5_3_PreviousInput_h, &pSrc->Memory5_3_PreviousInput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_a);
   memcpy(&pDst->lastSin_a, &pSrc->lastSin_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_d);
   memcpy(&pDst->lastCos_d, &pSrc->lastCos_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_e);
   memcpy(&pDst->lastSin_e, &pSrc->lastSin_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_h);
   memcpy(&pDst->lastCos_h, &pSrc->lastCos_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_d);
   memcpy(&pDst->lastSin_d, &pSrc->lastSin_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_ov);
   memcpy(&pDst->lastCos_ov, &pSrc->lastCos_ov, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_n);
   memcpy(&pDst->lastSin_n, &pSrc->lastSin_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_j);
   memcpy(&pDst->lastCos_j, &pSrc->lastCos_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inversion_DWORK1);
   memcpy(&pDst->inversion_DWORK1, &pSrc->inversion_DWORK1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inversion_DWORK3);
   memcpy(&pDst->inversion_DWORK3, &pSrc->inversion_DWORK3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inversion_DWORK4);
   memcpy(&pDst->inversion_DWORK4, &pSrc->inversion_DWORK4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK);
   memcpy(&pDst->Derivative_RWORK, &pSrc->Derivative_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_h);
   memcpy(&pDst->Derivative_RWORK_h, &pSrc->Derivative_RWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_b);
   memcpy(&pDst->Derivative_RWORK_b, &pSrc->Derivative_RWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_g);
   memcpy(&pDst->Derivative_RWORK_g, &pSrc->Derivative_RWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_hs);
   memcpy(&pDst->Derivative_RWORK_hs, &pSrc->Derivative_RWORK_hs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_f);
   memcpy(&pDst->Derivative_RWORK_f, &pSrc->Derivative_RWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_p);
   memcpy(&pDst->Derivative_RWORK_p, &pSrc->Derivative_RWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_b3);
   memcpy(&pDst->Derivative_RWORK_b3, &pSrc->Derivative_RWORK_b3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_b0);
   memcpy(&pDst->Derivative_RWORK_b0, &pSrc->Derivative_RWORK_b0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_l);
   memcpy(&pDst->Derivative_RWORK_l, &pSrc->Derivative_RWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_j);
   memcpy(&pDst->Derivative_RWORK_j, &pSrc->Derivative_RWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_m);
   memcpy(&pDst->Derivative_RWORK_m, &pSrc->Derivative_RWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_n);
   memcpy(&pDst->Derivative_RWORK_n, &pSrc->Derivative_RWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_pj);
   memcpy(&pDst->Derivative_RWORK_pj, &pSrc->Derivative_RWORK_pj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_m2);
   memcpy(&pDst->Derivative_RWORK_m2, &pSrc->Derivative_RWORK_m2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_a);
   memcpy(&pDst->Derivative_RWORK_a, &pSrc->Derivative_RWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Derivative_RWORK_m4);
   memcpy(&pDst->Derivative_RWORK_m4, &pSrc->Derivative_RWORK_m4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PipingTransportDelay1_RWORK);
   memcpy(&pDst->PipingTransportDelay1_RWORK, &pSrc->PipingTransportDelay1_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RTEConversion_RWORK);
   memcpy(&pDst->RTEConversion_RWORK, &pSrc->RTEConversion_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RTEConversion_RWORK_p);
   memcpy(&pDst->RTEConversion_RWORK_p, &pSrc->RTEConversion_RWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK);
   memcpy(&pDst->SFunction_RWORK, &pSrc->SFunction_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_p);
   memcpy(&pDst->SFunction_RWORK_p, &pSrc->SFunction_RWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_o);
   memcpy(&pDst->SFunction_RWORK_o, &pSrc->SFunction_RWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_b);
   memcpy(&pDst->SFunction_RWORK_b, &pSrc->SFunction_RWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_i);
   memcpy(&pDst->SFunction_RWORK_i, &pSrc->SFunction_RWORK_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_e);
   memcpy(&pDst->SFunction_RWORK_e, &pSrc->SFunction_RWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_id);
   memcpy(&pDst->SFunction_RWORK_id, &pSrc->SFunction_RWORK_id, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_f);
   memcpy(&pDst->SFunction_RWORK_f, &pSrc->SFunction_RWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_a);
   memcpy(&pDst->SFunction_RWORK_a, &pSrc->SFunction_RWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_l);
   memcpy(&pDst->SFunction_RWORK_l, &pSrc->SFunction_RWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_fz);
   memcpy(&pDst->SFunction_RWORK_fz, &pSrc->SFunction_RWORK_fz, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_RWORK_g);
   memcpy(&pDst->SFunction_RWORK_g, &pSrc->SFunction_RWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->GeneratedFilterBlock_circBuf);
   memcpy(&pDst->GeneratedFilterBlock_circBuf, &pSrc->GeneratedFilterBlock_circBuf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->GeneratedFilterBlock_circBuf_i);
   memcpy(&pDst->GeneratedFilterBlock_circBuf_i, &pSrc->GeneratedFilterBlock_circBuf_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable);
   memcpy(&pDst->systemEnable, &pSrc->systemEnable, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_m);
   memcpy(&pDst->systemEnable_m, &pSrc->systemEnable_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_o);
   memcpy(&pDst->systemEnable_o, &pSrc->systemEnable_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_c);
   memcpy(&pDst->systemEnable_c, &pSrc->systemEnable_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_d);
   memcpy(&pDst->systemEnable_d, &pSrc->systemEnable_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_h);
   memcpy(&pDst->systemEnable_h, &pSrc->systemEnable_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_mi);
   memcpy(&pDst->systemEnable_mi, &pSrc->systemEnable_mi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->inversion_DWORK2);
   memcpy(&pDst->inversion_DWORK2, &pSrc->inversion_DWORK2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PipingTransportDelay1_IWORK);
   memcpy(&pDst->PipingTransportDelay1_IWORK, &pSrc->PipingTransportDelay1_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OpCtrl_IWORK);
   memcpy(&pDst->OpCtrl_IWORK, &pSrc->OpCtrl_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_h);
   memcpy(&pDst->SFunction_IWORK_h, &pSrc->SFunction_IWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_e);
   memcpy(&pDst->SFunction_IWORK_e, &pSrc->SFunction_IWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_p);
   memcpy(&pDst->SFunction_IWORK_p, &pSrc->SFunction_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_c);
   memcpy(&pDst->SFunction_IWORK_c, &pSrc->SFunction_IWORK_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_l);
   memcpy(&pDst->SFunction_IWORK_l, &pSrc->SFunction_IWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_n);
   memcpy(&pDst->SFunction_IWORK_n, &pSrc->SFunction_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_j);
   memcpy(&pDst->SFunction_IWORK_j, &pSrc->SFunction_IWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o);
   memcpy(&pDst->SFunction_IWORK_o, &pSrc->SFunction_IWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_or);
   memcpy(&pDst->SFunction_IWORK_or, &pSrc->SFunction_IWORK_or, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f);
   memcpy(&pDst->SFunction_IWORK_f, &pSrc->SFunction_IWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_i);
   memcpy(&pDst->SFunction_IWORK_i, &pSrc->SFunction_IWORK_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_nj);
   memcpy(&pDst->SFunction_IWORK_nj, &pSrc->SFunction_IWORK_nj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_lh);
   memcpy(&pDst->SFunction_IWORK_lh, &pSrc->SFunction_IWORK_lh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_k);
   memcpy(&pDst->SFunction_IWORK_k, &pSrc->SFunction_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_o4);
   memcpy(&pDst->SFunction_IWORK_o4, &pSrc->SFunction_IWORK_o4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_kp);
   memcpy(&pDst->SFunction_IWORK_kp, &pSrc->SFunction_IWORK_kp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_cd);
   memcpy(&pDst->SFunction_IWORK_cd, &pSrc->SFunction_IWORK_cd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_hs);
   memcpy(&pDst->SFunction_IWORK_hs, &pSrc->SFunction_IWORK_hs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_jx);
   memcpy(&pDst->SFunction_IWORK_jx, &pSrc->SFunction_IWORK_jx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_jp);
   memcpy(&pDst->SFunction_IWORK_jp, &pSrc->SFunction_IWORK_jp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->HitCrossing_MODE);
   memcpy(&pDst->HitCrossing_MODE, &pSrc->HitCrossing_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_o);
   memcpy(&pDst->DelayInput1_DSTATE_o, &pSrc->DelayInput1_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_cg);
   memcpy(&pDst->UnitDelay_DSTATE_cg, &pSrc->UnitDelay_DSTATE_cg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_na);
   memcpy(&pDst->UnitDelay_DSTATE_na, &pSrc->UnitDelay_DSTATE_na, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_m);
   memcpy(&pDst->UnitDelay_DSTATE_m, &pSrc->UnitDelay_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_d);
   memcpy(&pDst->DelayInput1_DSTATE_d, &pSrc->DelayInput1_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_l);
   memcpy(&pDst->DelayInput1_DSTATE_l, &pSrc->DelayInput1_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->delay_DSTATE);
   memcpy(&pDst->delay_DSTATE, &pSrc->delay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_ot);
   memcpy(&pDst->DelayInput1_DSTATE_ot, &pSrc->DelayInput1_DSTATE_ot, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput2_DSTATE);
   memcpy(&pDst->DelayInput2_DSTATE, &pSrc->DelayInput2_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_k);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_k, &pSrc->FixPtUnitDelay1_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_g);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_g, &pSrc->FixPtUnitDelay1_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->PmIntegrator_PrevResetState);
   memcpy(&pDst->PmIntegrator_PrevResetState, &pSrc->PmIntegrator_PrevResetState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_PrevResetState);
   memcpy(&pDst->Integrator_PrevResetState, &pSrc->Integrator_PrevResetState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_PrevResetState);
   memcpy(&pDst->Filter_PrevResetState, &pSrc->Filter_PrevResetState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_PrevResetState_h);
   memcpy(&pDst->Integrator_PrevResetState_h, &pSrc->Integrator_PrevResetState_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_PrevResetState_n);
   memcpy(&pDst->Filter_PrevResetState_n, &pSrc->Filter_PrevResetState_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_PrevResetState_m);
   memcpy(&pDst->Integrator_PrevResetState_m, &pSrc->Integrator_PrevResetState_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_PrevResetState_i);
   memcpy(&pDst->Filter_PrevResetState_i, &pSrc->Filter_PrevResetState_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_PrevResetState_g);
   memcpy(&pDst->Integrator_PrevResetState_g, &pSrc->Integrator_PrevResetState_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_PrevResetState_g);
   memcpy(&pDst->Filter_PrevResetState_g, &pSrc->Filter_PrevResetState_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_PrevResetState_i);
   memcpy(&pDst->Integrator_PrevResetState_i, &pSrc->Integrator_PrevResetState_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->fIntegrator_PrevResetState);
   memcpy(&pDst->fIntegrator_PrevResetState, &pSrc->fIntegrator_PrevResetState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integrator_PrevResetState_hf);
   memcpy(&pDst->Integrator_PrevResetState_hf, &pSrc->Integrator_PrevResetState_hf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Filter_PrevResetState_nr);
   memcpy(&pDst->Filter_PrevResetState_nr, &pSrc->Filter_PrevResetState_nr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->LoadThermalMass50degMBTU_PrevRe);
   memcpy(&pDst->LoadThermalMass50degMBTU_PrevRe, &pSrc->LoadThermalMass50degMBTU_PrevRe, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrtor_PrevReset);
   memcpy(&pDst->DiscreteTimeIntegrtor_PrevReset, &pSrc->DiscreteTimeIntegrtor_PrevReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrtor_PrevRes_n);
   memcpy(&pDst->DiscreteTimeIntegrtor_PrevRes_n, &pSrc->DiscreteTimeIntegrtor_PrevRes_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_PrevRese);
   memcpy(&pDst->DiscreteTimeIntegrator_PrevRese, &pSrc->DiscreteTimeIntegrator_PrevRese, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrtor_PrevRes_d);
   memcpy(&pDst->DiscreteTimeIntegrtor_PrevRes_d, &pSrc->DiscreteTimeIntegrtor_PrevRes_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->icLoad);
   memcpy(&pDst->icLoad, &pSrc->icLoad, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->icLoad_i);
   memcpy(&pDst->icLoad_i, &pSrc->icLoad_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->icLoad_b);
   memcpy(&pDst->icLoad_b, &pSrc->icLoad_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_a);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_a, &pSrc->Integ4_SYSTEM_ENABLE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_at);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_at, &pSrc->Integ4_SYSTEM_ENABLE_at, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_l);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_l, &pSrc->Integ4_SYSTEM_ENABLE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_h);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_h, &pSrc->Integ4_SYSTEM_ENABLE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_k);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_k, &pSrc->Integ4_SYSTEM_ENABLE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_f);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_f, &pSrc->Integ4_SYSTEM_ENABLE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ak);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ak, &pSrc->Integ4_SYSTEM_ENABLE_ak, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_n);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_n, &pSrc->Integ4_SYSTEM_ENABLE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_k3);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_k3, &pSrc->Integ4_SYSTEM_ENABLE_k3, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_lc);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_lc, &pSrc->Integ4_SYSTEM_ENABLE_lc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fu);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fu, &pSrc->Integ4_SYSTEM_ENABLE_fu, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fn);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fn, &pSrc->Integ4_SYSTEM_ENABLE_fn, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_o);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_o, &pSrc->Integ4_SYSTEM_ENABLE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_p);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_p, &pSrc->Integ4_SYSTEM_ENABLE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_m);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_m, &pSrc->Integ4_SYSTEM_ENABLE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_j);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_j, &pSrc->Integ4_SYSTEM_ENABLE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_oe);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_oe, &pSrc->Integ4_SYSTEM_ENABLE_oe, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_jf);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_jf, &pSrc->Integ4_SYSTEM_ENABLE_jf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_ke);
   memcpy(&pDst->Memory_PreviousInput_ke, &pSrc->Memory_PreviousInput_ke, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_e);
   memcpy(&pDst->Memory_PreviousInput_e, &pSrc->Memory_PreviousInput_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_p);
   memcpy(&pDst->Memory_PreviousInput_p, &pSrc->Memory_PreviousInput_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_l);
   memcpy(&pDst->Memory_PreviousInput_l, &pSrc->Memory_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_a);
   memcpy(&pDst->Memory_PreviousInput_a, &pSrc->Memory_PreviousInput_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_i);
   memcpy(&pDst->Memory_PreviousInput_i, &pSrc->Memory_PreviousInput_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_o);
   memcpy(&pDst->Memory_PreviousInput_o, &pSrc->Memory_PreviousInput_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_n);
   memcpy(&pDst->Memory_PreviousInput_n, &pSrc->Memory_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_b);
   memcpy(&pDst->Memory1_PreviousInput_b, &pSrc->Memory1_PreviousInput_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_ov);
   memcpy(&pDst->Memory_PreviousInput_ov, &pSrc->Memory_PreviousInput_ov, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_n2);
   memcpy(&pDst->Memory_PreviousInput_n2, &pSrc->Memory_PreviousInput_n2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_m);
   memcpy(&pDst->Memory_PreviousInput_m, &pSrc->Memory_PreviousInput_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_av);
   memcpy(&pDst->Memory_PreviousInput_av, &pSrc->Memory_PreviousInput_av, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE);
   memcpy(&pDst->AutomaticGainControl_MODE, &pSrc->AutomaticGainControl_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE_j);
   memcpy(&pDst->AutomaticGainControl_MODE_j, &pSrc->AutomaticGainControl_MODE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE);
   memcpy(&pDst->RMS_MODE, &pSrc->RMS_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE);
   memcpy(&pDst->TrueRMS_MODE, &pSrc->TrueRMS_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE_m);
   memcpy(&pDst->AutomaticGainControl_MODE_m, &pSrc->AutomaticGainControl_MODE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE_d);
   memcpy(&pDst->RMS_MODE_d, &pSrc->RMS_MODE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE_e);
   memcpy(&pDst->TrueRMS_MODE_e, &pSrc->TrueRMS_MODE_e, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.blkStateChange);
   memcpy(&pDst->ModelData.blkStateChange, &pSrc->ModelData.blkStateChange, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeF);
   memcpy(&pDst->ModelData.odeF, &pSrc->ModelData.odeF, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeY);
   memcpy(&pDst->ModelData.odeY, &pSrc->ModelData.odeY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

