/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE, &pSrc->DiscreteTimeIntegrator_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n1);
   memcpy(&pDst->UnitDelay_DSTATE_n1, &pSrc->UnitDelay_DSTATE_n1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput);
   memcpy(&pDst->Memory1_PreviousInput, &pSrc->Memory1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory8_PreviousInput);
   memcpy(&pDst->Memory8_PreviousInput, &pSrc->Memory8_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_1_PreviousInput);
   memcpy(&pDst->Memory3_1_PreviousInput, &pSrc->Memory3_1_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_2_PreviousInput);
   memcpy(&pDst->Memory3_2_PreviousInput, &pSrc->Memory3_2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_3_PreviousInput);
   memcpy(&pDst->Memory3_3_PreviousInput, &pSrc->Memory3_3_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_4_PreviousInput);
   memcpy(&pDst->Memory3_4_PreviousInput, &pSrc->Memory3_4_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_5_PreviousInput);
   memcpy(&pDst->Memory3_5_PreviousInput, &pSrc->Memory3_5_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_6_PreviousInput);
   memcpy(&pDst->Memory3_6_PreviousInput, &pSrc->Memory3_6_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_7_PreviousInput);
   memcpy(&pDst->Memory3_7_PreviousInput, &pSrc->Memory3_7_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_b);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_b, &pSrc->DiscreteTimeIntegrator_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_8_PreviousInput);
   memcpy(&pDst->Memory3_8_PreviousInput, &pSrc->Memory3_8_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_9_PreviousInput);
   memcpy(&pDst->Memory3_9_PreviousInput, &pSrc->Memory3_9_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_10_PreviousInput);
   memcpy(&pDst->Memory3_10_PreviousInput, &pSrc->Memory3_10_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory1_PreviousInput_e);
   memcpy(&pDst->Memory1_PreviousInput_e, &pSrc->Memory1_PreviousInput_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory8_PreviousInput_e);
   memcpy(&pDst->Memory8_PreviousInput_e, &pSrc->Memory8_PreviousInput_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_1_PreviousInput_p);
   memcpy(&pDst->Memory3_1_PreviousInput_p, &pSrc->Memory3_1_PreviousInput_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_2_PreviousInput_l);
   memcpy(&pDst->Memory3_2_PreviousInput_l, &pSrc->Memory3_2_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_3_PreviousInput_n);
   memcpy(&pDst->Memory3_3_PreviousInput_n, &pSrc->Memory3_3_PreviousInput_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_4_PreviousInput_g);
   memcpy(&pDst->Memory3_4_PreviousInput_g, &pSrc->Memory3_4_PreviousInput_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_5_PreviousInput_d);
   memcpy(&pDst->Memory3_5_PreviousInput_d, &pSrc->Memory3_5_PreviousInput_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_p);
   memcpy(&pDst->UD_DSTATE_p, &pSrc->UD_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_6_PreviousInput_m);
   memcpy(&pDst->Memory3_6_PreviousInput_m, &pSrc->Memory3_6_PreviousInput_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_7_PreviousInput_c);
   memcpy(&pDst->Memory3_7_PreviousInput_c, &pSrc->Memory3_7_PreviousInput_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_8_PreviousInput_d);
   memcpy(&pDst->Memory3_8_PreviousInput_d, &pSrc->Memory3_8_PreviousInput_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_9_PreviousInput_l);
   memcpy(&pDst->Memory3_9_PreviousInput_l, &pSrc->Memory3_9_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory3_10_PreviousInput_e);
   memcpy(&pDst->Memory3_10_PreviousInput_e, &pSrc->Memory3_10_PreviousInput_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Unwrap_Prev);
   memcpy(&pDst->Unwrap_Prev, &pSrc->Unwrap_Prev, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Unwrap_Cumsum);
   memcpy(&pDst->Unwrap_Cumsum, &pSrc->Unwrap_Cumsum, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput);
   memcpy(&pDst->Memory2_PreviousInput, &pSrc->Memory2_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory9_PreviousInput);
   memcpy(&pDst->Memory9_PreviousInput, &pSrc->Memory9_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Unwrap_Prev_a);
   memcpy(&pDst->Unwrap_Prev_a, &pSrc->Unwrap_Prev_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_e);
   memcpy(&pDst->UnitDelay_DSTATE_e, &pSrc->UnitDelay_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Unwrap_Cumsum_b);
   memcpy(&pDst->Unwrap_Cumsum_b, &pSrc->Unwrap_Cumsum_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory2_PreviousInput_j);
   memcpy(&pDst->Memory2_PreviousInput_j, &pSrc->Memory2_PreviousInput_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory9_PreviousInput_i);
   memcpy(&pDst->Memory9_PreviousInput_i, &pSrc->Memory9_PreviousInput_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_b);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_b, &pSrc->DiscreteStateSpace_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_k);
   memcpy(&pDst->UnitDelay_DSTATE_k, &pSrc->UnitDelay_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_e);
   memcpy(&pDst->SFunction_IWORK_e, &pSrc->SFunction_IWORK_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_i);
   memcpy(&pDst->Integ4_DSTATE_i, &pSrc->Integ4_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_h);
   memcpy(&pDst->SFunction_IWORK_h, &pSrc->SFunction_IWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_l);
   memcpy(&pDst->SFunction_IWORK_l, &pSrc->SFunction_IWORK_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_j);
   memcpy(&pDst->SFunction_IWORK_j, &pSrc->SFunction_IWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_es);
   memcpy(&pDst->SFunction_IWORK_es, &pSrc->SFunction_IWORK_es, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f);
   memcpy(&pDst->SFunction_IWORK_f, &pSrc->SFunction_IWORK_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_hj);
   memcpy(&pDst->SFunction_IWORK_hj, &pSrc->SFunction_IWORK_hj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_d);
   memcpy(&pDst->SFunction_IWORK_d, &pSrc->SFunction_IWORK_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_a);
   memcpy(&pDst->SFunction_IWORK_a, &pSrc->SFunction_IWORK_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_fv);
   memcpy(&pDst->SFunction_IWORK_fv, &pSrc->SFunction_IWORK_fv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_jj);
   memcpy(&pDst->SFunction_IWORK_jj, &pSrc->SFunction_IWORK_jj, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_kt);
   memcpy(&pDst->UnitDelay_DSTATE_kt, &pSrc->UnitDelay_DSTATE_kt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_k);
   memcpy(&pDst->SFunction_IWORK_k, &pSrc->SFunction_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_p);
   memcpy(&pDst->SFunction_IWORK_p, &pSrc->SFunction_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_hc);
   memcpy(&pDst->SFunction_IWORK_hc, &pSrc->SFunction_IWORK_hc, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_fs);
   memcpy(&pDst->SFunction_IWORK_fs, &pSrc->SFunction_IWORK_fs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ff);
   memcpy(&pDst->SFunction_IWORK_ff, &pSrc->SFunction_IWORK_ff, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_g);
   memcpy(&pDst->SFunction_IWORK_g, &pSrc->SFunction_IWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_p1);
   memcpy(&pDst->SFunction_IWORK_p1, &pSrc->SFunction_IWORK_p1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_c);
   memcpy(&pDst->SFunction_IWORK_c, &pSrc->SFunction_IWORK_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_a2);
   memcpy(&pDst->SFunction_IWORK_a2, &pSrc->SFunction_IWORK_a2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_n);
   memcpy(&pDst->SFunction_IWORK_n, &pSrc->SFunction_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE, &pSrc->FixPtUnitDelay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_m);
   memcpy(&pDst->SFunction_IWORK_m, &pSrc->SFunction_IWORK_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_nd);
   memcpy(&pDst->SFunction_IWORK_nd, &pSrc->SFunction_IWORK_nd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_f5);
   memcpy(&pDst->SFunction_IWORK_f5, &pSrc->SFunction_IWORK_f5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_dt);
   memcpy(&pDst->SFunction_IWORK_dt, &pSrc->SFunction_IWORK_dt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_n);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_n, &pSrc->FixPtUnitDelay1_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_n0);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_n0, &pSrc->FixPtUnitDelay1_DSTATE_n0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_k);
   memcpy(&pDst->DelayInput1_DSTATE_k, &pSrc->DelayInput1_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_b);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_b, &pSrc->FixPtUnitDelay1_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_a);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_a, &pSrc->FixPtUnitDelay1_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_o);
   memcpy(&pDst->DelayInput1_DSTATE_o, &pSrc->DelayInput1_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_c);
   memcpy(&pDst->Integ4_DSTATE_c, &pSrc->Integ4_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_o);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_o, &pSrc->Integ4_SYSTEM_ENABLE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_k);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_k, &pSrc->Integ4_SYSTEM_ENABLE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_d);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_d, &pSrc->Integ4_SYSTEM_ENABLE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_b);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_b, &pSrc->Integ4_SYSTEM_ENABLE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_e);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_e, &pSrc->Integ4_SYSTEM_ENABLE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_eh);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_eh, &pSrc->Integ4_SYSTEM_ENABLE_eh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_od);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_od, &pSrc->Integ4_SYSTEM_ENABLE_od, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_l);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_l, &pSrc->Integ4_SYSTEM_ENABLE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_c);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_c, &pSrc->Integ4_SYSTEM_ENABLE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h);
   memcpy(&pDst->UnitDelay_DSTATE_h, &pSrc->UnitDelay_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_lg);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_lg, &pSrc->Integ4_SYSTEM_ENABLE_lg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_f);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_f, &pSrc->Integ4_SYSTEM_ENABLE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fs);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fs, &pSrc->Integ4_SYSTEM_ENABLE_fs, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_h);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_h, &pSrc->Integ4_SYSTEM_ENABLE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_bf);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_bf, &pSrc->Integ4_SYSTEM_ENABLE_bf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_os);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_os, &pSrc->Integ4_SYSTEM_ENABLE_os, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_l4);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_l4, &pSrc->Integ4_SYSTEM_ENABLE_l4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_hr);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_hr, &pSrc->Integ4_SYSTEM_ENABLE_hr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_kt);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_kt, &pSrc->Integ4_SYSTEM_ENABLE_kt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ds);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ds, &pSrc->Integ4_SYSTEM_ENABLE_ds, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_a);
   memcpy(&pDst->Integ4_DSTATE_a, &pSrc->Integ4_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ll);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ll, &pSrc->Integ4_SYSTEM_ENABLE_ll, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_fr);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_fr, &pSrc->Integ4_SYSTEM_ENABLE_fr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_m);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_m, &pSrc->Integ4_SYSTEM_ENABLE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_ei);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_ei, &pSrc->Integ4_SYSTEM_ENABLE_ei, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Unwrap_FirstStep);
   memcpy(&pDst->Unwrap_FirstStep, &pSrc->Unwrap_FirstStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_o);
   memcpy(&pDst->Memory_PreviousInput_o, &pSrc->Memory_PreviousInput_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_g);
   memcpy(&pDst->Memory_PreviousInput_g, &pSrc->Memory_PreviousInput_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Unwrap_FirstStep_b);
   memcpy(&pDst->Unwrap_FirstStep_b, &pSrc->Unwrap_FirstStep_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_h);
   memcpy(&pDst->Memory_PreviousInput_h, &pSrc->Memory_PreviousInput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_d);
   memcpy(&pDst->UnitDelay_DSTATE_d, &pSrc->UnitDelay_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE);
   memcpy(&pDst->AutomaticGainControl_MODE, &pSrc->AutomaticGainControl_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE_c);
   memcpy(&pDst->AutomaticGainControl_MODE_c, &pSrc->AutomaticGainControl_MODE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE_m);
   memcpy(&pDst->AutomaticGainControl_MODE_m, &pSrc->AutomaticGainControl_MODE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->AutomaticGainControl_MODE_o);
   memcpy(&pDst->AutomaticGainControl_MODE_o, &pSrc->AutomaticGainControl_MODE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->sf_trip_outmng_a);
   memcpy(&pDst->sf_trip_outmng_a, &pSrc->sf_trip_outmng_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->sf_Relays_c);
   memcpy(&pDst->sf_Relays_c, &pSrc->sf_Relays_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->sf_trip_outmng);
   memcpy(&pDst->sf_trip_outmng, &pSrc->sf_trip_outmng, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->sf_Relays);
   memcpy(&pDst->sf_Relays, &pSrc->sf_Relays, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE);
   memcpy(&pDst->DelayInput1_DSTATE, &pSrc->DelayInput1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_id);
   memcpy(&pDst->Integ4_DSTATE_id, &pSrc->Integ4_DSTATE_id, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_m);
   memcpy(&pDst->UnitDelay_DSTATE_m, &pSrc->UnitDelay_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_j);
   memcpy(&pDst->UnitDelay_DSTATE_j, &pSrc->UnitDelay_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ez);
   memcpy(&pDst->UnitDelay_DSTATE_ez, &pSrc->UnitDelay_DSTATE_ez, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_h);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_h, &pSrc->DiscreteTimeIntegrator_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_o);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_o, &pSrc->DiscreteTimeIntegrator_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_d);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_d, &pSrc->DiscreteTimeIntegrator_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_m);
   memcpy(&pDst->Integ4_DSTATE_m, &pSrc->Integ4_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ed);
   memcpy(&pDst->UnitDelay_DSTATE_ed, &pSrc->UnitDelay_DSTATE_ed, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_a);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_a, &pSrc->DiscreteTimeIntegrator_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_e);
   memcpy(&pDst->UD_DSTATE_e, &pSrc->UD_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_i);
   memcpy(&pDst->UnitDelay_DSTATE_i, &pSrc->UnitDelay_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_l);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_l, &pSrc->DiscreteStateSpace_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_oi);
   memcpy(&pDst->Integ4_DSTATE_oi, &pSrc->Integ4_DSTATE_oi, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_g);
   memcpy(&pDst->UnitDelay_DSTATE_g, &pSrc->UnitDelay_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_iq);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_iq, &pSrc->DiscreteTimeIntegrator_DSTAT_iq, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_b);
   memcpy(&pDst->UD_DSTATE_b, &pSrc->UD_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE);
   memcpy(&pDst->UD_DSTATE, &pSrc->UD_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_a);
   memcpy(&pDst->UnitDelay_DSTATE_a, &pSrc->UnitDelay_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_k);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_k, &pSrc->DiscreteStateSpace_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_p);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_p, &pSrc->DiscreteTimeIntegrator_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_h);
   memcpy(&pDst->Integ4_DSTATE_h, &pSrc->Integ4_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_au);
   memcpy(&pDst->UnitDelay_DSTATE_au, &pSrc->UnitDelay_DSTATE_au, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_j);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_j, &pSrc->DiscreteTimeIntegrator_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_n);
   memcpy(&pDst->UD_DSTATE_n, &pSrc->UD_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_o);
   memcpy(&pDst->UnitDelay_DSTATE_o, &pSrc->UnitDelay_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_d);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_d, &pSrc->DiscreteStateSpace_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_b);
   memcpy(&pDst->UnitDelay_DSTATE_b, &pSrc->UnitDelay_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_l);
   memcpy(&pDst->UnitDelay_DSTATE_l, &pSrc->UnitDelay_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_m);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_m, &pSrc->DiscreteTimeIntegrator_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_cw);
   memcpy(&pDst->Integ4_DSTATE_cw, &pSrc->Integ4_DSTATE_cw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_jt);
   memcpy(&pDst->UnitDelay_DSTATE_jt, &pSrc->UnitDelay_DSTATE_jt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_jr);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_jr, &pSrc->DiscreteTimeIntegrator_DSTAT_jr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_m);
   memcpy(&pDst->UD_DSTATE_m, &pSrc->UD_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_an);
   memcpy(&pDst->UnitDelay_DSTATE_an, &pSrc->UnitDelay_DSTATE_an, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_j);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_j, &pSrc->DiscreteStateSpace_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_hh);
   memcpy(&pDst->UnitDelay_DSTATE_hh, &pSrc->UnitDelay_DSTATE_hh, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_e);
   memcpy(&pDst->Integ4_DSTATE_e, &pSrc->Integ4_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_e5);
   memcpy(&pDst->UnitDelay_DSTATE_e5, &pSrc->UnitDelay_DSTATE_e5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE);
   memcpy(&pDst->DiscreteStateSpace_DSTATE, &pSrc->DiscreteStateSpace_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->FixPtUnitDelay1_DSTATE_g);
   memcpy(&pDst->FixPtUnitDelay1_DSTATE_g, &pSrc->FixPtUnitDelay1_DSTATE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_f);
   memcpy(&pDst->Integ4_DSTATE_f, &pSrc->Integ4_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_p);
   memcpy(&pDst->UnitDelay_DSTATE_p, &pSrc->UnitDelay_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_k);
   memcpy(&pDst->Integ4_DSTATE_k, &pSrc->Integ4_DSTATE_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_jf);
   memcpy(&pDst->UnitDelay_DSTATE_jf, &pSrc->UnitDelay_DSTATE_jf, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DelayInput1_DSTATE_a);
   memcpy(&pDst->DelayInput1_DSTATE_a, &pSrc->DelayInput1_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_p);
   memcpy(&pDst->Integ4_DSTATE_p, &pSrc->Integ4_DSTATE_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ea);
   memcpy(&pDst->UnitDelay_DSTATE_ea, &pSrc->UnitDelay_DSTATE_ea, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_jm);
   memcpy(&pDst->UnitDelay_DSTATE_jm, &pSrc->UnitDelay_DSTATE_jm, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_im);
   memcpy(&pDst->UnitDelay_DSTATE_im, &pSrc->UnitDelay_DSTATE_im, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n);
   memcpy(&pDst->UnitDelay_DSTATE_n, &pSrc->UnitDelay_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_ii);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_ii, &pSrc->DiscreteTimeIntegrator_DSTAT_ii, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_f);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_f, &pSrc->DiscreteTimeIntegrator_DSTATE_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_pp);
   memcpy(&pDst->Integ4_DSTATE_pp, &pSrc->Integ4_DSTATE_pp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_l0);
   memcpy(&pDst->UnitDelay_DSTATE_l0, &pSrc->UnitDelay_DSTATE_l0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTAT_pw);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTAT_pw, &pSrc->DiscreteTimeIntegrator_DSTAT_pw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_h);
   memcpy(&pDst->UD_DSTATE_h, &pSrc->UD_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_gp);
   memcpy(&pDst->UnitDelay_DSTATE_gp, &pSrc->UnitDelay_DSTATE_gp, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_h);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_h, &pSrc->DiscreteStateSpace_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ei);
   memcpy(&pDst->Integ4_DSTATE_ei, &pSrc->Integ4_DSTATE_ei, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_lo);
   memcpy(&pDst->UnitDelay_DSTATE_lo, &pSrc->UnitDelay_DSTATE_lo, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_i);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_i, &pSrc->DiscreteTimeIntegrator_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteTimeIntegrator_DSTATE_c);
   memcpy(&pDst->DiscreteTimeIntegrator_DSTATE_c, &pSrc->DiscreteTimeIntegrator_DSTATE_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UD_DSTATE_i);
   memcpy(&pDst->UD_DSTATE_i, &pSrc->UD_DSTATE_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_pk);
   memcpy(&pDst->UnitDelay_DSTATE_pk, &pSrc->UnitDelay_DSTATE_pk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->DiscreteStateSpace_DSTATE_m);
   memcpy(&pDst->DiscreteStateSpace_DSTATE_m, &pSrc->DiscreteStateSpace_DSTATE_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_pe);
   memcpy(&pDst->Integ4_DSTATE_pe, &pSrc->Integ4_DSTATE_pe, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_pr);
   memcpy(&pDst->UnitDelay_DSTATE_pr, &pSrc->UnitDelay_DSTATE_pr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_d);
   memcpy(&pDst->Integ4_DSTATE_d, &pSrc->Integ4_DSTATE_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_hw);
   memcpy(&pDst->UnitDelay_DSTATE_hw, &pSrc->UnitDelay_DSTATE_hw, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_my);
   memcpy(&pDst->Integ4_DSTATE_my, &pSrc->Integ4_DSTATE_my, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ir);
   memcpy(&pDst->UnitDelay_DSTATE_ir, &pSrc->UnitDelay_DSTATE_ir, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_o);
   memcpy(&pDst->Integ4_DSTATE_o, &pSrc->Integ4_DSTATE_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_ip);
   memcpy(&pDst->Integ4_DSTATE_ip, &pSrc->Integ4_DSTATE_ip, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_lv);
   memcpy(&pDst->UnitDelay_DSTATE_lv, &pSrc->UnitDelay_DSTATE_lv, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_er);
   memcpy(&pDst->Integ4_DSTATE_er, &pSrc->Integ4_DSTATE_er, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_go);
   memcpy(&pDst->UnitDelay_DSTATE_go, &pSrc->UnitDelay_DSTATE_go, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_h4);
   memcpy(&pDst->Integ4_DSTATE_h4, &pSrc->Integ4_DSTATE_h4, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_ku);
   memcpy(&pDst->UnitDelay_DSTATE_ku, &pSrc->UnitDelay_DSTATE_ku, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_n);
   memcpy(&pDst->Integ4_DSTATE_n, &pSrc->Integ4_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_b5);
   memcpy(&pDst->UnitDelay_DSTATE_b5, &pSrc->UnitDelay_DSTATE_b5, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_j);
   memcpy(&pDst->Integ4_DSTATE_j, &pSrc->Integ4_DSTATE_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_hf);
   memcpy(&pDst->UnitDelay_DSTATE_hf, &pSrc->UnitDelay_DSTATE_hf, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.blkStateChange);
   memcpy(&pDst->ModelData.blkStateChange, &pSrc->ModelData.blkStateChange, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

